### ISSUE TITLE
Show estimated time of route

### ISSUE THREAD

**Issue by slinlee** [cogsci/wigglemap#16]

**Comment by andrewdanks** [comment]
this can be calculated just in the frontend pretty easily.

need a mockup of how this should be presented

**Comment by epan** [comment]
trip distance and time should be provided by google api

On Wed, Oct 24, 2012 at 3:57 PM, Andrew Danks notifications@github.comwrote:

> this can be calculated just in the frontend pretty easily.
> 
> need a mockup of how this should be presented
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/andrewdanks/reroute/issues/16#issuecomment-9760152.

## 

Eric

**Comment by epan** [comment]
Suggested visualization under the map area: http://cl.ly/image/3L3p3E0u021L

**Comment by dhchow** [comment]
Just added labels for this info that pop up on the top left. Feel free to be like "move that shit"
