### ISSUE TITLE
Need a Name

### ISSUE THREAD

**Issue by epan** [cogsci/wigglemap#19]

**Comment by epan** [comment]
Look what @vickiheart did guys!
![sketch 1](http://cl.ly/image/1r2J3u052n38/photo%201.JPG)
![sketch 2](http://cl.ly/image/3I402z1z180t/photo%202.JPG)
![sketch 3](http://cl.ly/image/3z150k3W1T2C/photo%203.JPG)
![sketch 4](http://cl.ly/image/3V1r2f0I3u1M/photo%204.JPG)
cc: @kmiyashiro @andrewdanks @dhchow @ericxtang 

What about trying the shape of the wiggle for the W? I like putting a bike in there somehow. maybe also using the "sharrows" http://www.sfmta.com/cms/bsafe/28372.html and I some of them look like street markings.

**Comment by epan** [comment]
You guys, this is tough!
![PRO-CON](http://cl.ly/image/3C1x0s0P0w0v/Screen%20Shot%202012-10-25%20at%2012.29.42%20AM.png)
@kmiyashiro @dhchow @ericxtang @andrewdanks @slinlee 
VOTE?

**Comment by andrewdanks** [comment]
Tough one. I like both, but if I had a gun to my head, I'd pick wiggl.me

**Comment by kmiyashiro** [comment]
I like wiggle with e, any variation.

**Comment by vickiheart** [comment]
Another option is wggle.com, which domainr says "possibly available"
Not sure what that means. And not sure how I feel about the lack of vowels. Although that seems to be the trend (flickr, rdio, etc)

**Comment by andrewdanks** [comment]
According to http://whois.domaintools.com/wggle.com, it's taken

**Comment by vickiheart** [comment]
wggle.co
wggle.io

**Comment by epan** [comment]
I don't like dropping the "i" in wiggle since it is so instructive towards how to read it aloud. without it, it could be "waggle, wiggle, wuggle, woggle…" etc

Found some variations at www.namecheap.com which has a pretty decent search tool:
![domain and prices](http://cl.ly/image/2m01173P2N3t/Screen%20Shot%202012-10-26%20at%201.25.05%20AM.png)
heywiggle.com
hellowiggle.com
hiwiggle.com
wigglme.com
wiggl.me
wigglin.com
wiggl.in

**Comment by epan** [comment]
@slinlee what do you think?

**Comment by epan** [comment]
wigglem.com is available hahahaha

**Comment by epan** [comment]
Ok guys, I went ahead with www.wiggl.me :)

**Comment by epan** [comment]
Still need a logo though and so if @vickiheart is interested in helping us narrow down, it's still assigned to her and I'll leave it open and move it to Later milestone now.

**Comment by vickiheart** [comment]
@epan Still interested but I have no illustrator skillz. I'll continue working on it this weekend :) Are we doing a meetup?

yay for wiggl.me!

**Comment by kmiyashiro** [comment]
We have a name! Close?

**Comment by andrewdanks** [comment]
For a super short domain, wigl.me is available.

**Comment by epan** [comment]
Yes I thought I closed it?

I bought and have wiggl.me for a whole year if we want to use that :)

**Comment by slinlee** [comment]
Taking WiggleMap as the name. I'll open a new issue for a logo?
