### ISSUE TITLE
Prettify the current segment indicator

### ISSUE THREAD

**Issue by epan** [cogsci/wigglemap#25]
Can we try a nicer way to show which segment the user is on other than the red border?

Kelly suggested an inner glow.
If not clear enough, maybe we can do a border-top or something else.
Ideas welcome!

**Comment by epan** [comment]
Another idea is to have current segment a little taller than the others. Check out this example: http://www.directr.co/movie/5fm9w 

How hard is that @kmiyashiro @dhchow ?

I was thinking inner glow would get difficult to see when the segments are thin. And this example could also be the effect for hover.

**Comment by kmiyashiro** [comment]
ez

**Comment by dhchow** [comment]
Yeah should be pretty straightforward. I'll play around with this tonight.

**Comment by kmiyashiro** [comment]
I actually did this this morning :)

**Comment by dhchow** [comment]
Sweet! Does this mean you're quitting your job :)

**Comment by kmiyashiro** [comment]
Work starts at 11! I work on other stuff in the morning.
