### ISSUE TITLE
Show elevation data

### ISSUE THREAD

**Issue by dhchow** [cogsci/wigglemap#35]
Not clear as to how this will look, but I think it'd be useful to at least show the area of greatest elevation delta on the timeline/map/both. That way the person can anticipate where the "toughest" climb is before they head out.

Of course, showing all of the elevation data we have would also be helpful, though I'm not sure how much more helpful it will be. Depends if people really care about the whole ride or just the extreme points.

**Comment by epan** [comment]
Good ideas! I'm thinking this is a duplicate of https://github.com/andrewdanks/reroute/issues/21 and if you agree, go ahead and close it, otherwise, feel free to clarify. Thanks Diana!

**Comment by dhchow** [comment]
Yup! Looks like a duplicate. Closing.
