### ISSUE TITLE
Page isn't loading right in Chrome on Macbook Air?

### ISSUE THREAD

**Issue by vickiheart** [cogsci/wigglemap#43]
Hi guys, when I load wigglemap.com on chrome on my air it doesn't show the whole page unless I zoom out a lot. I don't see the start / end and etc.

**Comment by epan** [comment]
Can you reproduce this bug? If so, let us know step by step, please. Thanks!

**Comment by vickiheart** [comment]
It's fixed (sometime in between then and now, looks like something changed). Thanks!
