### ISSUE TITLE
Prettify the App Page

### ISSUE THREAD

**Issue by epan** [cogsci/wigglemap#45]
Moved discussion and task list for this issue to Hackpad for collaboration: https://hackpad.com/Y3jja4y8lAx#Prettify-wigglemap

Current App
![Current App @ 640](http://cl.ly/image/0Y1b2L2C1k2F/Screen%20Shot%202012-10-29%20at%2010.53.02%20AM.png)

Updated UI (Work in Progress)
![Updated UI WIP](http://cl.ly/image/3n0Y0n0G0k1k/Screen%20Shot%202012-10-29%20at%2010.54.20%20AM.png)

**Comment by slinlee** [comment]
I added some of the spec'd styling on to the secondary view container.

**Comment by slinlee** [comment]
Made the 'Find a route' button large size, which matches the height of the input fields. It's not orange though.

**Comment by epan** [comment]
Moved discussion and task list for this issue to Hackpad for collaboration: https://hackpad.com/Y3jja4y8lAx#Prettify-wigglemap

**Comment by epan** [comment]
Good enough for now. Great job, team :)
