### ISSUE TITLE
Interaction with timeline

### ISSUE THREAD

**Issue by epan** [cogsci/wigglemap#5]
If you click on a part of the timeline it will jump to that position in the route and in streetview.

**Comment by vickiheart** [comment]
Missed first part of discussion so let me know if this is already obvious or answered:

Can someone explain the bottom green bar to me? Seems to be turn by turn distance, but I don't understand the green vs. white. One idea is to label the portions as someone would think of the directions in their mind: 17th to Market to Franklin.

Also, I think it would be great to display this as a line indicating elevation (like a line graph) so you can see progress, as well as slope. Did we already think about integrating this?

**Comment by kmiyashiro** [comment]
It's supposed to be a timeline and the green represents how safe it is. Mo green == mo safe. Direction labels are in another issue I think. Having an elevation vis is something we thought of, but I think the line-chart isn't captured anywhere.

**Comment by epan** [comment]
I'll add the issue

On Wed, Oct 24, 2012 at 5:59 PM, Kelly Miyashiro
notifications@github.comwrote:

> It's supposed to be a timeline and the green represents how safe it is. Mo
> green == mo safe. Direction labels are in another issue I think. Having an
> elevation vis is something we thought of, but I think the line-chart isn't
> captured anywhere.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/andrewdanks/reroute/issues/5#issuecomment-9762726.

## 

Eric
