### ISSUE TITLE
Title and caption need to be aligned

### ISSUE THREAD

**Issue by andrewdanks** [cogsci/wigglemap#57]
Need to fix the alignment of the title and caption:

![](http://i.imgur.com/knPqz.png)

**Comment by epan** [comment]
It's more important that the caption and the inputs are aligned to each other. The bigger question is should the caption and inputs be in the center or always left-aligned?

**Comment by andrewdanks** [comment]
I think it's okay if the caption doesn't align with the input, because it's already aligned with the box itself. Not being aligned with the title, though, looks funny.
